include: package:lints/recommended.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  ## TODO Remove next 2 lines
  ## Bug https://stackoverflow.com/questions/62630553/analysis-options-yaml-the-included-file-not-found
  exclude:
    - "example/**"
    - "**/*.g.dart"

linter:
  rules:
    - use_null_aware_elements
